### ISSUE TITLE
Using blue in lowercase does not change color to blue.

### ISSUE THREAD

**Issue by Jhone-Paul** [SAED2906/color-console-logger#2]
There is a double declaration of 'BLUE' and one should be 'blue'. 

How to replicate:
`
const { colorLogger, Colors } = require('color-console-logger');

colorLogger("This should be a blue message", "blue");
colorLogger("This is a blue message", "BLUE");
`

**Comment by SAED2906** [comment]
Thank you for bringing this to my attention, I will fix it now. 👍🏻

**Comment by Jhone-Paul** [comment]
Similarly for the double declaration of grey.

**Comment by SAED2906** [comment]
Ok published the changes to npm as seen here:
https://www.npmjs.com/package/color-console-logger/v/1.0.6
